### ISSUE TITLE
404 from npm

### ISSUE THREAD

**Issue by anthager** [brandonpittman/tailwindcss-plugin-delight#1]
Hi! Great plugin! We're currently using this in a project and this morning our builds started failing due to getting 404s from npm on this package. Are this something you're aware of/planning on solving? I guess it could be on npm's side of things as well. 

Thanks in advance!

**Comment by brandonpittman** [comment]
@anthager It'll be fixed this time tomorrow. Sorry about that.

**Comment by anthager** [comment]
@brandonpittman No worries, thanks!

**Comment by brandonpittman** [comment]
@anthager Should be okay now.

https://www.npmjs.com/package/tailwindcss-plugin-delight
